version: "3.3"
services:
  fulltext-aggregator:
    image: fulltext-aggregator:latest
    build: ./image
    environment:
      - OUTPUT_DIR=/output
      - DUMP_BASE_URL=${DUMP_BASE_URL:-ftp://download.europeana.eu/newspapers/fulltext/edm_issue}
      - QUEUE_SIZE_LIMIT=${QUEUE_SIZE_LIMIT:-1024}
      - BLOCK_SIZE=${BLOCK_SIZE:-65536}
      - DEBUG=${DEBUG:-false}
    volumes:
      - "${LOCAL_OUTPUT_DIR:-./output}:/output"
